### ISSUE TITLE
Feedback Técnico

### ISSUE THREAD

**Issue by AnaflaviaDiaz** [MaryKattyVO/lim20181-Track-FE-markdown-list#33]
## Cosas que hiciste bien.

- Recorrer archivo, extraer links y texto de links en un archivo markdown.

- Recorrer carpetas, extraer links y texto de links en un archivo markdown.

- Determinar el status de respuesta HTTP de los links encontrados.

- Sacar el total de links que se encuentran en la ruta escrita, total de links únicos y total links rotos.

- Trabajaste con issues y milestone.

## Cosas por mejorar.

- La función mdLinks debería retornar una promesa donde tú imprimas el resultado de esa promesa.
https://github.com/MaryKattyVO/lim20181-Track-FE-markdown-list/blob/281799b40928cdb4421958a18b1b2bcd16337b79/cli.js#L24 donde esto debería ser así: `		mdlinks(file, options).then(response => console.log(response))`
- Cada iteración que haces para sacar los resultados de las opciones escritas en CLI (`--stats , --validate`) lo haces con un `console.log() cuando deberías imprimirlo en el resultado de la promesa en la función mdLinks`
- Cuando no escribes ninguna opción en CLI debería retornar *link* *texto* y *ruta*. 
- Trata de mejorar tus consultas según las opciones, que solo retornen lo que el usuario requiere 
![image](https://user-images.githubusercontent.com/15807118/45002419-f16c5300-af9b-11e8-98e2-2dfc02ba018b.png) este ejemplo de tu readme lo describe.

## Cosas por hacer

- Te recomiendo que vayas actualizando tu readme describiendo el uso de tu librería.
- Subas tu package en npm.
- Empieza a hacer tus test desde ahora para que puedas corregir a tiempo tus funciones. Guíate de aquí: https://jestjs.io/docs/en/asynchronous .
- En tu proyecto tienes carpetas y archivos que no deberían estar agrégalos en tu `.gitignore`
![image](https://user-images.githubusercontent.com/15807118/45002567-a4897c00-af9d-11e8-8255-3fa4dc27fbd0.png)

Mucha suerte!

**Comment by MaryKattyVO** [comment]
Gracias Anaflavia por tu feedback, voy a mejorarlo.
